### PR TITLE
updatedb made fast

### PR DESCRIPTION
**Pull request by adityapatadia**
- This will also reduce RAM usage as streams are used and files are not read as a whole.

### CODE REVIEW

**Comment by adityapatadia** [comment]
@bluesmoon this makes updatedb very fast while reducing RAM usage. Please consider merge and if possible release version.

**Comment by adityapatadia** [comment]
@bluesmoon apologies for pinging u again but this is critical for us to get out. Can you please look into merging this?

**Review by bluesmoon — APPROVED** [review]

**Comment by adityapatadia** [comment]
@bluesmoon thanks for merging. When you release, you might also want to change repo description. It won't work with node 0.6 anymore. Minimum version required should be node 12.

**Comment by bluesmoon** [comment]
Got it. Been meaning to do that.

**Pull request merged**
