### PR TITLE
Update async to address security vulnerability

### PR DESCRIPTION
**Pull request by byumark**
https://security.snyk.io/vuln/SNYK-JS-ASYNC-2441827

### CODE REVIEW

**Comment by bluesmoon** [comment]
I'd like to accept this PR, but I'm traveling at the moment and can't verify that upgrading async to a new major version doesn't break anything. 

If you can show via test results or command line output that this change is safe, I'll merge it in.

**Comment by byumark** [comment]
Thanks, @bluesmoon . No rush but here's the results of the test. 

image

**Comment by ckortekaas** [comment]
FYI, Async 2.6.4 is also now available that backports the CVE fix

**Comment by bluesmoon** [comment]
merged #238 instead

**Pull request closed without merging**
